import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../../css/globals.css'
import '../../css/index.css'
import '../../css/logIn.css'
import '../../css/navbar.css'
import '../../css/register.css'
import '../../css/sr.css'
import '../../css/ImpactLayout.css'
import '../../css/Home.css'
import '../../css/footer.css'
import '../../css/Donation.css'
import '../../css/chi.css'
import '../../css/blog.css'
import '../../css/Article.css'
import '../../css/aboutUs.css'
import { NextAuthProvider } from '../../components/middlewareAuths/nextAuthProvider'
import Analytics from '@vercel/analytics'
import 'bootstrap/dist/css/bootstrap.min.css'
import '@fortawesome/fontawesome-svg-core/styles.css'
import '@fortawesome/fontawesome-free/css/all.min.css'
import {config} from '@fortawesome/fontawesome-svg-core'

config.autoAddCss=false

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Changia - Children Home Platform',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextAuthProvider>
        {children}
        {/* <Analytics /> */}
      </NextAuthProvider>
      </body>
    </html>
  )
}
